apiVersion: cilium.io/v2alpha1
kind: CiliumBGPClusterConfig
metadata:
  name: bgp-cluster-config
spec:
  nodeSelector:
    matchLabels:
      kubernetes.io/os: linux #peer with all nodes
  bgpInstances:
    - name: "instance-65512"
      localASN: 65512
      peers:
        - name: "peer-65510"
          peerASN: 65510
          peerAddress: 172.16.8.1
          peerConfigRef:
            name: "cilium-peer-config"
---
apiVersion: cilium.io/v2alpha1
kind: CiliumBGPPeerConfig
metadata:
  name: cilium-peer-config
spec:
  timers:
    holdTimeSeconds: 9
    keepAliveTimeSeconds: 3
  gracefulRestart:
    enabled: true
  families:
    - afi: ipv4
      safi: unicast
      advertisements:
        matchLabels:
          bgp.cilium.io/advertise: main-routes
---
apiVersion: cilium.io/v2alpha1
kind: CiliumBGPAdvertisement
metadata:
  name: bgp-advertisements
  labels:
    bgp.cilium.io/advertise: main-routes
spec:
  advertisements:
    - advertisementType: Service
      service:
        addresses:
          - LoadBalancerIP
      selector:
        matchExpressions:
          - key: io.kubernetes.service.namespace
            operator: In
            values:
              - gateway
          - key: io.kubernetes.service.name
            operator: In
            values:
              - cilium-gateway-gateway-internal
              - cilium-gateway-gateway-external
          
    - advertisementType: PodCIDR
---
apiVersion: cilium.io/v2alpha1
kind: CiliumLoadBalancerIPPool
metadata:
  name: main-pool
  namespace: kube-system
spec:
  blocks:
    - cidr: "172.16.18.0/27"
      # This provides IPs from 172.16.18.1 to 172.16.18.30
      # Reserve specific IPs for known services:
      # - 172.16.18.2: Gateway External
      # - 172.16.18.30: Gateway Internal
      # - Remaining 30 IPs for other LoadBalancer services
  allowFirstLastIPs: "No"