apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: csi-proxmox
helmCharts:
  - name: proxmox-csi-plugin
    repo: oci://ghcr.io/sergelogvinov/charts
    version: 0.5.3
    releaseName: csi-proxmox
    includeCRDs: true
    namespace: csi-proxmox
    valuesFile: values.yaml
resources:
  - ns.yaml
  - external-secret.yaml