apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources: 
 - ns.yaml
 - external-secret.yaml


helmCharts:
- name: velero
  repo: https://vmware-tanzu.github.io/helm-charts
  version: 11.3.2
  releaseName: velero
  includeCRDs: true
  namespace: velero
  valuesFile: values.yaml