apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kube-system

patches:
  - path: corefile-patch.yaml
    target:
      kind: ConfigMap
      name: coredns
      namespace: kube-system