apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# 1. Set the namespace for EVERYTHING in this stack
namespace: media

# 2. Create the infrastructure first
resources:
  - ns.yaml
  - appdata-pvc.yaml
  - shared-media-pvc.yaml

  - sonarr/