apiVersion: apps/v1
kind: Deployment
metadata:
  name: overseer
  namespace: overseer
  labels:
      app: overseer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: overseer
  template:
    metadata:
      labels:
        app: overseer
    spec:
      containers:
        - name: overseer
          image: lscr.io/linuxserver/overseer:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 7878
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "America/Toronto"
          volumeMounts:
            - name: appdata
              mountPath: /config
              subPath: appdata/linuxserver-overseer-2/config
      volumes:
        - name: appdata
          persistentVolumeClaim:
            claimName: pvc-appdata