apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: booklore

resources:
  - ns.yaml
  - book-library-pvc.yaml
  - bookdrop-pvc.yaml
  - appdata-pvc.yaml
  - externalsecret.yaml
  - deployment.yaml
  - db-backup.yaml
  - httproute.yaml
  - svc.yaml
