storageClass:
  create: true
  name: nfs-storageclass-media
  provisioner: nfs.csi.k8s.io
  parameters:
    server: 10.10.1.46
    share: /pool-0/media
  reclaimPolicy: Retain
  volumeBindingMode: Immediate
  mountOptions:
    - "nfsvers=4"
    - "nolock"
    - "tcp"