apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: sonarr

resources:
  - ns.yaml
  - appdata-pvc.yaml
  - shared-media-pvc.yaml
  - deployment.yaml
  - httproute.yaml
  - svc.yaml