apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: sonarr

resources:
  - deployment.yaml
  - httproute.yaml
  - svc.yaml
  # - svc.yaml
  # - pvc.yaml
  # - jellyfin-media-pvc.yaml
  # - deployment.yaml
  # - httproute.yaml