apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: traefik-internal-cert
  namespace: traefik
spec:
  secretName: traefik-internal-cert-tls
  dnsNames:
    - traefik.internal.mcmn.io
  issuerRef:
    name: cloudflare-cluster-issuer
    kind: ClusterIssuer