apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: traefik-portal-credentials
  namespace: traefik
spec:
  refreshInterval: "1h"
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password
  target:
    name: traefik-portal-credentials
    creationPolicy: Owner
  data:
    # Superuser credentials
    - secretKey: username
      remoteRef:
        key: traefik-admin
        property: username
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: password
      remoteRef:
        key: traefik-admin
        property: password
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None